global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'devops-node'
    static_configs:
      - targets: ['DEVOPS_IP:9100']

  - job_name: 'devops-nginx'
    static_configs:
      - targets: ['DEVOPS_IP:9113']

rule_files:
  - /etc/prometheus/rules/prometheus.rules.yml
