global:
  resolve_timeout: 5m

route:
  receiver: 'console'

receivers:
  - name: 'console'
  - name: 'email'
    email_configs:
      - to: 'you@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'alertmanager'
        auth_password: 'password'
